apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: certificado-tls
  namespace: front
spec:
  secretName: certificate-nginx
  issuerRef:
    name: letsencrypt
  commonName: iamcloud.ddns.net
  #Renew before 15 days of expiry
  renewBefore: 360h
  acme:
    config:
    - http01:
        ingress: ingress-resource
      domains:
      - iamcloud.ddns.net