apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: front
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: a16dancasrom@iam.cat
    privateKeySecretRef:
      name: letsencrypt
    http01: {}

